name: main-deploy-cicd

on: push

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ayazzz/githubactionsws:v1.0.${{github.run_number}}.latest